<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translation2 [
        <!ELEMENT translation2 (languages,pages)>
        <!ELEMENT languages (lang*)>
        <!ELEMENT lang (name?,meta?,error_text?,encoding?)>
        <!ATTLIST lang id ID #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT meta (#PCDATA)>
        <!ELEMENT error_text (#PCDATA)>
        <!ELEMENT encoding (#PCDATA)>
        <!ELEMENT pages (page*)>
        <!ELEMENT page (string*)>
        <!ATTLIST page key CDATA #REQUIRED>
        <!ELEMENT string (tr*)>
        <!ATTLIST string key CDATA #REQUIRED>
        <!ELEMENT tr (#PCDATA)>
        <!ATTLIST tr lang IDREF #REQUIRED>
        ]>

<translation2>
    <languages>
        <lang id="ru">
            <name> Русский </name>
            <meta> a:7:{s:6:&quot;active&quot;;s:1:&quot;1&quot;;s:10:&quot;is_default&quot;;b:0;s:5:&quot;theme&quot;;s:0:&quot;&quot;;s:11:&quot;date_format&quot;;s:8:&quot;%d.%m.%Y&quot;;s:17:&quot;decimal_separator&quot;;s:1:&quot;.&quot;;s:19:&quot;thousands_separator&quot;;s:1:&quot;,&quot;;s:8:&quot;decimals&quot;;s:1:&quot;1&quot;;} </meta>
            <error_text></error_text>
            <encoding> utf-8 </encoding>
        </lang>
    </languages>
    <pages>
        <page key="PhrasesInTemplates">
            <string key="There are no properties selected. Please choose at least one to export.">
                <tr lang="ru"> Не выбрано ни одного свойства объявления. Выберите как минимум одно поле для экспорта. </tr>
            </string>
            <string key="Listing Large Picture Width">
                <tr lang="ru"> Ширина большой картинки объявления </tr>
            </string>
            <string key="Listing Large Picture Height">
                <tr lang="ru"> Высота большой картинки объявления </tr>
            </string>
            <string key="Cannot save none existing search">
                <tr lang="ru"> Невозможно сохранить не существующий поиск </tr>
            </string>
            <string key="Response for deleted and inactive listings">
                <tr lang="ru"> Ответ для удаленных и неактивных объявлений </tr>
            </string>
            <string key="The default response in according to HTTP/1.1 Status Code standards &lt;a href=&quot;http://tools.ietf.org/html/rfc2616&quot; title=&quot;RFC 2616&quot;&gt;RFC 2616&lt;/a&gt;:">
                <tr lang="ru"> Ответ по умолчанию в соответствии со стандартом кодов ответа HTTP/1.1 &lt;a href=&quot;http://tools.ietf.org/html/rfc2616&quot; title=&quot;RFC 2616&quot;&gt;RFC 2616&lt;/a&gt;: </tr>
            </string>
            <string key="404 Not Found - for deleted listings">
                <tr lang="ru"> 404 Не найдено - для удаленных объявлений </tr>
            </string>
            <string key="403 Forbidden - for inactive listings">
                <tr lang="ru"> 403 Запрещено - для неактивных объявлений </tr>
            </string>
            <string key="303 See Other - both for deleted and inactive listings, redirecting to a page with the response code 200 OK:">
                <tr lang="ru"> 303 Смотреть в другом месте - и для удаленных, и для неактивных объявлений, с перенаправлением на страницу с кодом ответа &quot;200 Окей&quot;: </tr>
            </string>
            <string key="view this page">
                <tr lang="ru"> посмотреть эту страницу </tr>
            </string>
            <string key="Please specify the &lt;a href=&quot;$siteBackendUrl/site_pages/&quot;&gt;Site Page&lt;/a&gt; URI for the redirect as follows: /example-page/ &lt;br /&gt; You should create this page before using it.">
                <tr lang="ru"> Пожалуйста, укажите URI &lt;a href=&quot;$siteBackendUrl/site_pages/&quot;&gt;страницы сайта&lt;/a&gt; для перенаправления следующим образом: /example-page/ &lt;br /&gt; Вам необходимо создать эту страницу, прежде чем использовать ее. </tr>
            </string>
            <string key="Sorry!">
                <tr lang="ru"> Извините, </tr>
            </string>
            <string key="This listing was deleted or has already been sold. To see more listings please go to the &lt;a href=&quot;$siteUrl/search/Car/&quot;&gt;Advanced Search&lt;/a&gt;.">
                <tr lang="ru"> это объявление было удалено или уже неактуально. Пожалуйста, воспользуйтесь &lt;a href=&quot;$siteUrl/search/Car/&quot;&gt;расширенным поиском&lt;/a&gt;, чтобы найти то, что вам нужно. </tr>
            </string>
            <string key="Thank you!">
                <tr lang="ru"> Спасибо! </tr>
            </string>
            <string key="Enable autocomplete for keyword search">
                <tr lang="ru"> Включить автозаполнение для поиска по ключевым словам </tr>
            </string>
            <string key="Reply to the comment">
                <tr lang="ru"> Ответить на комментарий </tr>
            </string>
            <string key="Reply to The Comment">
                <tr lang="ru"> Ответ на комментарий </tr>
            </string>
            <string key="Manage Booking">
                <tr lang="ru"> Управление бронированием </tr>
            </string>
            <string key="Add More Criteria">
                <tr lang="ru"> Добавить критерий </tr>
            </string>
            <string key="Select Payment Method">
                <tr lang="ru"> Выбор метода оплаты </tr>
            </string>
            <string key="Please fill in the required fields!">
                <tr lang="ru"> Пожалуйста, заполните обязательные поля! </tr>
            </string>
            <string key="Car Information &amp; Location">
                <tr lang="ru"> Основное </tr>
            </string>
            <string key="Car Information">
                <tr lang="ru"> Об автомобиле </tr>
            </string>
            <string key="Basic Information">
                <tr lang="ru"> Основная информация </tr>
            </string>
            <string key="Detailed Information">
                <tr lang="ru"> Подробная информация </tr>
            </string>
            <string key="Credits subtracted by administrator">
                <tr lang="ru"> Снятие кредитов администратором </tr>
            </string>
            <string key="with comment &apos;$comment&apos;">
                <tr lang="ru"> с комментарием &apos;$comment&apos; </tr>
            </string>
            <string key="Credits added by administrator">
                <tr lang="ru"> Добавление кредитов администратором </tr>
            </string>
            <string key="The Membership Plan for professional dealers who advertise a lot of bikes on behalf of their owners and thus are interested to pay less for each ad buying a Subscription Plan.">
                <tr lang="ru"> План подписки для профессиональных дилеров, которые рекламируют много мотоциклов или велосипедов от имени их владельцев, и, соответственно, заинтересованы платить меньше за каждое объявление, покупая подписку. </tr>
            </string>
            <string key="The following options were successfully enabled and will be activated on the &lt;a href=&quot;#listing$listingSid&quot;&gt;listing #$listingSid &quot;$listingCaption&quot;&lt;/a&gt; activation">
                <tr lang="ru"> Следующие опции были успешно включены для &lt;a href=&quot;#listing$listingSid&quot;&gt;объявления №$listingSid &quot;$listingCaption&quot;&lt;/a&gt; и будут активированы при активации объявления </tr>
            </string>
            <string key="The packages of all listings were synchronized with the modified Package.">
                <tr lang="ru"> Пакеты всех объявлений были синхронизированы с отредактированным Пакетом. </tr>
            </string>
            <string key="You cannot add language on demo version.">
                <tr lang="ru"> Вы не можете создавать языки в демо-версии. </tr>
            </string>
            <string key="You cannot import language on demo version.">
                <tr lang="ru"> Вы не можете импортировать языки в демо-версии. </tr>
            </string>
            <string key="Please &lt;a href=&quot;$addListingLink&quot;&gt;create a new listing&lt;/a&gt;, or add more options to &lt;a href=&quot;$myListingsLink&quot;&gt;your existing ads&lt;/a&gt; to promote them better.">
                <tr lang="ru"> Пожалуйста, &lt;a href=&quot;$addListingLink&quot;&gt;создайте новое объявление&lt;/a&gt; или добавьте больше опций для &lt;a href=&quot;$myListingsLink&quot;&gt;ваших существующих объявлений&lt;/a&gt;, чтобы увеличить их популярность. </tr>
            </string>
            <string key="You have successfully subscribed to the membership plan: $membershipPlanName, and you can &lt;a href=&quot;$subscriptionLink&quot;&gt;view your current subscription&lt;/a&gt;.">
                <tr lang="ru"> Вы успешно поменяли план подписки на $membershipPlanName, и теперь вы можете &lt;a href=&quot;$subscriptionLink&quot;&gt;просмотреть вашу текущую подписку&lt;/a&gt;. </tr>
            </string>
            <string key="The listing #$listingSid &quot;$listingCaption&quot; was removed from the basket.">
                <tr lang="ru"> Объявление №$listingSid &quot;$listingCaption&quot; было удалено из корзины. </tr>
            </string>
            <string key="The option $optionName was deleted for the listing #$listingSid &quot;$listingCaption&quot;.">
                <tr lang="ru"> Опция $optionName для объявления №$listingSid &quot;$listingCaption&quot; была удалена. </tr>
            </string>
            <string key="Language and Regional Settings">
                <tr lang="ru"> Язык и региональные настройки </tr>
            </string>
            <string key="Language and Regional Settings Configuration">
                <tr lang="ru"> Конфигурация языка и региональных настроек </tr>
            </string>
            <string key="Email And Notifications">
                <tr lang="ru"> Почта и уведомления </tr>
            </string>
            <string key="Social Networks">
                <tr lang="ru"> Социальные сети </tr>
            </string>
            <string key="Pending transactions are the payments that have not been completed automatically by the payment gateway due to some error and require administrator&apos;s endorsement. In certain cases, when you pay in cash or via money transfer, the website administrator needs more time to manually complete your payment. If you think that your pending transaction should have already been completed, please &lt;a href=&quot;$url&quot;&gt;contact the administrator&lt;/a&gt;.">
                <tr lang="ru"> Незавершенные транзакции — это платежи, которые не были автоматически завершены платежным шлюзом из-за какой-то ошибки и требуют подтверждения администратором. В определенных случаях, когда вы платите наличными или денежным переводом, администратору сайта требуется больше времени, чтобы вручную завершить ваш платеж. Если вы считаете, что ваша незавершенная транзакция уже должна быть обработана, пожалуйста, &lt;a href=&quot;$url&quot;&gt;свяжитесь с администратором&lt;/a&gt;. </tr>
            </string>
            <string key="Add options">
                <tr lang="ru"> Добавить опции </tr>
            </string>
            <string key="The basket is filtered by the listing #$sid. &lt;a href=&quot;$url&quot;&gt;Show all basket&lt;/a&gt;">
                <tr lang="ru"> Корзина отфильтрована по объявлению №$sid. &lt;a href=&quot;$url&quot;&gt;Показать всю корзину&lt;/a&gt;. </tr>
            </string>
            <string key="Activation">
                <tr lang="ru"> Активация </tr>
            </string>
            <string key="Your basket is empty. Please &lt;a href=&quot;$addListingLink&quot;&gt;create a new listing&lt;/a&gt;, or add more options to &lt;a href=&quot;$myListingsLink&quot;&gt;your existing ads&lt;/a&gt; to promote them better.">
                <tr lang="ru"> Ваша корзина пуста. Пожалуйста, &lt;a href=&quot;$addListingLink&quot;&gt;создайте новое объявление&lt;/a&gt; или добавьте больше опций для &lt;a href=&quot;$myListingsLink&quot;&gt;ваших существующих объявлений&lt;/a&gt;, чтобы увеличить их популярность. </tr>
            </string>
            <string key="Your basket is empty">
                <tr lang="ru"> Ваша корзина пуста </tr>
            </string>
            <string key="Please note that the endorsed payment contains the following deleted listings:">
                <tr lang="ru"> Пожалуйста, обратите внимание, что завершенный платеж содержит следующие удаленные объявления: </tr>
            </string>
            <string key="Listing Features">
                <tr lang="ru"> Опции объявления </tr>
            </string>
            <string key="Enable paid listing features:">
                <tr lang="ru"> Включить платные опции для объявления: </tr>
            </string>
            <string key="Save Listing &amp; Add Pictures">
                <tr lang="ru"> Сохранить и добавить фото </tr>
            </string>
            <string key="Buy more credits">
                <tr lang="ru"> Купить еще кредитов </tr>
            </string>
            <string key="Please keep in mind that the conditions of new Listing Package may reduce the number of listing pictures and prohibit video uploads.">
                <tr lang="ru"> Пожалуйста, обратите внимание на то, что условия нового Пакета объявлений могут сократить количество картинок в объявлении и запретить загрузку видео. </tr>
            </string>
            <string key="PDF Export">
                <tr lang="ru"> Экспорт в PDF </tr>
            </string>
            <string key="You have successfully purchased all items from the basket for $priceWithCurrency. The transaction number is $transaction_id. Thank you!">
                <tr lang="ru"> Вы успешно купили все услуги, добавленные вами в корзину, за $priceWithCurrency. Номер вашей транзакции - $transaction_id. Спасибо! </tr>
            </string>
            <string key="Front End">
                <tr lang="ru"> Пользовательская часть сайта </tr>
            </string>
            <string key="You cannot edit sub-administrators on demo version.">
                <tr lang="ru"> Вы не можете редактировать субадминистраторов в демо-версии. </tr>
            </string>
            <string key="You cannot edit API code on demo version.">
                <tr lang="ru"> Вы не можете редактировать код приложения в демо-версии. </tr>
            </string>
            <string key="You cannot edit listing main currency on demo version.">
                <tr lang="ru"> Вы не можете редактировать основную валюту в объявлениях в демо-версии. </tr>
            </string>
            <string key="You cannot edit the list of available currencies on demo version.">
                <tr lang="ru"> Вы не можете менять список доступных валют на демо-версии. </tr>
            </string>
            <string key="NumberOfGroupedListings">
                <tr lang="ru"> объявлений </tr>
            </string>
            <string key="There are no listings available that match your search criteria. Please try to &lt;a href=&quot;$link&quot;&gt;broaden your search criteria&lt;/a&gt;.">
                <tr lang="ru"> По вашему запросу ничего не найдено. Попробуйте &lt;a href=&quot;$link&quot;&gt;расширить критерии поиска&lt;/a&gt;. </tr>
            </string>
            <string key="The user $username was successfully made untrusted.">
                <tr lang="ru"> Пользователь $username был успешно переведен в группу недоверенных пользователей. </tr>
            </string>
            <string key="The user $username was successfully made trusted.">
                <tr lang="ru"> Пользователь $username был успешно переведен в группу доверенных пользователей. </tr>
            </string>
            <string key="Please copy the permanent link of this comment to your clipboard">
                <tr lang="ru"> Пожалуйста, скопируйте постоянную ссылку к этому комментарию в буфер обмена </tr>
            </string>
            <string key="Add Listing Comment">
                <tr lang="ru"> Добавить комментарий к объявлению </tr>
            </string>
            <string key="Condition">
                <tr lang="ru"> Состояние </tr>
            </string>
            <string key="New">
                <tr lang="ru"> Новый </tr>
            </string>
            <string key="Used">
                <tr lang="ru"> Подержанный </tr>
            </string>
            <string key="This payment gateway does not have a test mode and thus cannot be used on demo version.">
                <tr lang="ru"> У этого платежного шлюза нет тестового режима, и поэтому его нельзя использовать на демо-версии. </tr>
            </string>
            <string key="Add New Make/Model Request">
                <tr lang="ru"> Запрос на добавление новой марки/модели </tr>
            </string>
            <string key="notify us">
                <tr lang="ru"> сообщите нам </tr>
            </string>
            <string key="Please $link if some makes or models are missing. We will be happy to add them to our list!">
                <tr lang="ru"> Пожалуйста, $link, если какие-то марки или модели отсутствуют. Мы будем рады добавить их в наш список! </tr>
            </string>
            <string key="Show Decimal Part For Converted Money-type Fields">
                <tr lang="ru"> Показывать десятичную часть для сконвертированных полей типа &quot;деньги&quot; </tr>
            </string>
            <string key="Price $selectedCurrency">
                <tr lang="ru"> Цена, $selectedCurrency </tr>
            </string>
            <string key="Search Listings On Map">
                <tr lang="ru"> Поиск объявлений на карте </tr>
            </string>
            <string key="Search listings on map templates">
                <tr lang="ru"> Шаблоны поиска объявлений на карте </tr>
            </string>
            <string key="Featured Listing Slider">
                <tr lang="ru"> Слайдер горячих объявлений </tr>
            </string>
            <string key="Featured Listing Slider templates">
                <tr lang="ru"> Шаблоны слайдера горячих объявлений </tr>
            </string>
            <string key="PDF Export templates">
                <tr lang="ru"> Шаблоны экспорта в PDF </tr>
            </string>
            <string key="WebMoney payment gateway templates">
                <tr lang="ru"> Шаблоны WebMoney </tr>
            </string>
            <string key="Yandex Money payment gateway templates">
                <tr lang="ru"> Шаблоны Яндекс Деньги </tr>
            </string>
            <string key="Back to search form">
                <tr lang="ru"> Вернуться на форму поиска </tr>
            </string>
            <string key="Recent Tweets templates">
                <tr lang="ru"> Шаблоны свежих твитов </tr>
            </string>
            <string key="Ads on map templates">
                <tr lang="ru"> Шаблоны поиска и отображения объявлений на карте </tr>
            </string>
            <string key="Listing Repost">
                <tr lang="ru"> Публикация объявлений </tr>
            </string>
            <string key="Find On Map">
                <tr lang="ru"> Найти на карте </tr>
            </string>
            <string key="Ads On Map">
                <tr lang="ru"> Поиск и отображение объявлений на карте </tr>
            </string>
            <string key="Ads On Map Configuration">
                <tr lang="ru"> Настройки поиска и отображения объявлений на карте </tr>
            </string>
            <string key="Default Location">
                <tr lang="ru"> Местоположение по умолчанию </tr>
            </string>
            <string key="Are you sure that you want to delete this sub-administrator?">
                <tr lang="ru"> Вы уверены, что хотите удалить этого субадминистратора? </tr>
            </string>
            <string key="Sub-Administrators">
                <tr lang="ru"> Cубадминистраторы </tr>
            </string>
            <string key="Add New Sub-Administrator">
                <tr lang="ru"> Добавить нового субадминистратора </tr>
            </string>
            <string key="Edit Sub-Administrator Info">
                <tr lang="ru"> Редактировать данные субадминистратора </tr>
            </string>
            <string key="You have no permissions to access this section.">
                <tr lang="ru"> У вас нет доступа в этот раздел. </tr>
            </string>
            <string key="Website cannot get currency list.">
                <tr lang="ru"> Вебсайт не может получить список валют. </tr>
            </string>
            <string key="Listing main currency is not specified.">
                <tr lang="ru"> Основная валюта объявлений не указана. </tr>
            </string>
            <string key="An invalid API code was specified.">
                <tr lang="ru"> Указан неверный код API. </tr>
            </string>
            <string key="Website requested rates for an unsupported base currency.">
                <tr lang="ru"> Вебсайт запросил курс для неподдерживаемой валюты. </tr>
            </string>
            <string key="No API code was specified.">
                <tr lang="ru"> Не указан код API. </tr>
            </string>
            <string key="Website doesn&apos;t have permissions to access requested service.">
                <tr lang="ru"> Запрошенна услуга не доступна для вебсайта. </tr>
            </string>
            <string key="Website requested a non-existent resource.">
                <tr lang="ru"> Вебсайт запросил несуществующий сервис. </tr>
            </string>
            <string key="Website exceeded a maximum allowed number of requests and was blocked.">
                <tr lang="ru"> Вебсайт превысил максимально разрешенное количество запросов и был заблокирован. </tr>
            </string>
            <string key="Unknown currency was selected.">
                <tr lang="ru"> Выбрана неизвестная валюта. </tr>
            </string>
            <string key="Currency Converter">
                <tr lang="ru"> Конвертация валюты в листингах </tr>
            </string>
            <string key="Currency Converter Configuration">
                <tr lang="ru"> Конфигурация конвертации валюты в листингах </tr>
            </string>
            <string key="API Code">
                <tr lang="ru"> Код приложения </tr>
            </string>
            <string key="Listing Main Currency">
                <tr lang="ru"> Основная валюта в объявлениях </tr>
            </string>
            <string key="List Of Available Currencies">
                <tr lang="ru"> Список доступных валют </tr>
            </string>
            <string key="Show">
                <tr lang="ru"> Показать </tr>
            </string>
            <string key="Show On Map">
                <tr lang="ru"> Показать на карте </tr>
            </string>
            <string key="Show Search Results">
                <tr lang="ru"> Показать результаты поиска </tr>
            </string>
            <string key="Show Search Results On Map">
                <tr lang="ru"> Отображение результатов поиска на карте </tr>
            </string>
            <string key="Show search results on map templates">
                <tr lang="ru"> Шаблоны отображения результатов поиска на карте </tr>
            </string>
            <string key="Configuration of PDF Export">
                <tr lang="ru"> Настройка экспорта в PDF </tr>
            </string>
            <string key="Logo URL">
                <tr lang="ru"> URL для логотипа </tr>
            </string>
            <string key="Logo Width, px.">
                <tr lang="ru"> Ширина логотипа, пикс. </tr>
            </string>
            <string key="Header Height, px.">
                <tr lang="ru"> Высота шапки, пикс. </tr>
            </string>
            <string key="Header Font Size">
                <tr lang="ru"> Размер шрифта в шапке </tr>
            </string>
            <string key="Listing Font Size">
                <tr lang="ru"> Размер шрифта объявления </tr>
            </string>
            <string key="View Example">
                <tr lang="ru"> Посмотреть пример </tr>
            </string>
            <string key="Export to PDF">
                <tr lang="ru"> Экспорт в PDF </tr>
            </string>
            <string key="You cannot delete carousel images on demo version">
                <tr lang="ru"> Вы не можете удалять картинки в демо-версии. </tr>
            </string>
            <string key="You cannot send emails on demo version.">
                <tr lang="ru"> Вы не можете отправлять письма в демо версии. </tr>
            </string>
            <string key="You cannot create emails on demo version.">
                <tr lang="ru"> Вы не можете создавать письма в демо версии. </tr>
            </string>
            <string key="You cannot edit emails on demo version.">
                <tr lang="ru"> Вы не можете редактировать письма в демо версии. </tr>
            </string>
            <string key="The number in brackets next to a User Group shows the number of users subscribed to receive news from the website.">
                <tr lang="ru"> Рядом с названием группы в скобках указано количество пользователей, подписанных на рассылку от сайта. </tr>
            </string>
            <string key="MassEmailVariablesInfo">
                <tr lang="ru"> В сообщениях вы можете использовать следующие переменные:
                    &lt;ul&gt;
                    &lt;li&gt;{&amp;#36;user.username} - отображает логин пользователя&lt;/li&gt;
                    &lt;li&gt;{&amp;#36;user.FirstName} {&amp;#36;user.LastName} - отображает имя и фамилию пользователя&lt;/li&gt;
                    &lt;li&gt;{&amp;#36;GLOBALS.custom_settings.site_name} - отображает название сайта, указанное в Панели управления -&amp;gt; Настройки сайта&lt;/li&gt;
                    &lt;li&gt;{&amp;#36;GLOBALS.site_url} - отображает адрес сайта.&lt;/li&gt;
                    &lt;/ul&gt;
                    Пожалуйста, обратитесь к руководству пользователя в &lt;a href=&quot;$userManualArticleUrl&quot;&gt;User Manual -&amp;gt; Addons -&amp;gt; Mass Email&lt;/a&gt;, чтобы узнать больше о доступных переменных. </tr>
            </string>
            <string key="Report">
                <tr lang="ru"> Отчет </tr>
            </string>
            <string key="Sent Date &amp; Time">
                <tr lang="ru"> Дата и время отправки </tr>
            </string>
            <string key="Sent to">
                <tr lang="ru"> Кому </tr>
            </string>
            <string key="Subject">
                <tr lang="ru"> Тема </tr>
            </string>
            <string key="No attachments">
                <tr lang="ru"> Нет приложений </tr>
            </string>
            <string key="Recipients">
                <tr lang="ru"> Получатели </tr>
            </string>
            <string key="Body">
                <tr lang="ru"> Сообщение </tr>
            </string>
            <string key="Cancel dispatch">
                <tr lang="ru"> Отменить отправку </tr>
            </string>
            <string key="Sitemap">
                <tr lang="ru"> Карта сайта </tr>
            </string>
            <string key="Sitemap for Search Engines">
                <tr lang="ru"> Карта сайта для поисковых систем </tr>
            </string>
            <string key="Sitemap cache">
                <tr lang="ru"> Кэш для карты сайта </tr>
            </string>
            <string key="Rebuild">
                <tr lang="ru"> Пересобрать </tr>
            </string>
            <string key="Crawler visit frequency">
                <tr lang="ru"> Частота посещений для поисковых роботов </tr>
            </string>
            <string key="Always">
                <tr lang="ru"> Всегда </tr>
            </string>
            <string key="Hourly">
                <tr lang="ru"> Ежечасно </tr>
            </string>
            <string key="Sitemap is a list of website pages accessible to search engine crawlers, helping to improve search engine optimization of a website by making sure that all the pages can be found. &lt;br /&gt; This sitemap in the XML format is generated automatically. You can specify the sitemap.xml address in your robots.txt file for indexing by search engines as follows: &lt;br /&gt; SITEMAP: $FRONTEND_SITE_URL/sitemap.xml">
                <tr lang="ru"> Карта сайта — это список страниц вебсайта, доступных для роботов поисковых систем, помогающий улучшить поисковую оптимизацию вебсайта, гарантируя, что все необходимые страницы будут найдены поисковым роботом. &lt;br /&gt; Карта сайта в XML формате генерируется автоматически. Вы можете указать адрес вашей карты сайта в файле robots.txt для индексирования поисковыми системами следующим образом: &lt;br /&gt; SITEMAP: $FRONTEND_SITE_URL/sitemap.xml </tr>
            </string>
            <string key="The sitemap cache was successfully rebuilt.">
                <tr lang="ru"> Кэш для карты сайта был успешно пересобран. </tr>
            </string>
            <string key="Sort all tree values alphabetically ascending">
                <tr lang="ru"> Отсортировать все значения дерева в алфавитном порядке по возрастанию </tr>
            </string>
            <string key="The file with specified name already exists.">
                <tr lang="ru"> Файл с указанным именем уже существует. </tr>
            </string>
            <string key="Cannot create $fileName.">
                <tr lang="ru"> Невозможно создать $fileName. </tr>
            </string>
            <string key="SmsCoin Bank Secret">
                <tr lang="ru"> Секретный код SmsCoin </tr>
            </string>
            <string key="SmsCoin Bank ID">
                <tr lang="ru"> Название банка в SmsCoin </tr>
            </string>